### ISSUE TITLE
fac --continual aborts on error

### ISSUE THREAD

**Issue by flasheater** [droundy/fac#10]
When running `fac --continual` the process gets aborted when the build has an error. This is surprising because it seems to defeat the purpose to have to restart the process after (almost) any edit to source code.

I may have misunderstood the purpose of this flag, but I would like to use it, to gain continuous feedback from the compiler during development.

**Comment by droundy** [comment]
I've debated as to the proper behavior when `fac --continual` encounters an error.  The current behavior is thus not accidental, but it is open to improvement.  I think I agree that it would be better to wait for changes to any file that could affect the build and then try again.  It may not be a quick and easy change, however.

**Comment by droundy** [comment]
I've started work on this, but if you could work on getting a test working that would be great, as I have limited time just now, and this is a potentially tricky bit of code.  Thanks for the request!

**Comment by droundy** [comment]
This should be implemented, but still needs a test, and needs to be checked for memory leaks, so I'm leaving the issue open for now.
