### ISSUE TITLE
Feature request: only build when staged or committed

### ISSUE THREAD

**Issue by pcn** [droundy/fac#12]
Would it be possible to declare some builds will only be run in continual mode if they've been staged, others when committed, and the remainder works as per the current behaviour?

My use case is that I have a build process for a python that I would like to have fac build (create .whl files) and install (install into the currently active virtualenv).

Fac makes building these rules pretty easy, but it also discourages me from saving while I'm editing because once I save a file, the build and install gets run and the test service I'm writing for breaks on its own reload.

What I'd like is to be able to e.g. run a linter on save, run unit tests on stage, and build and deploy only on commit.  Is that sort of distinction possible with fac as it is now?

If this isn't directly possible via git, perhaps an even better option would be a subprocess that provides filenames that have changed, so I could write a script that waits on git status changes and inotify changes, and informs fac which files have been  modified so it can determine the appropriate action based on that change?

**Comment by droundy** [comment]
I'm not sure I like the complexity that would be needed to have distinct targets on distinct triggers.

You could script part of this today by running fac --continual linter-output, which would make fac only run the linter on save.  Triggering fac on staging or commit could be done with git hooks.  I'm not sure of the safety of running two fac builds on the same repo simultaneously, though.  Could lead to incorrect builds... which would be a bug.

I think the best solution here would be to ensure that running two fac instances at once is okay, which should enable what you want.  I don't know of any specific bugs, but haven't tried this and would expect trouble.

**Comment by droundy** [comment]
I have another and perhaps better idea as to how to implement this idea.  I realized that running multiple fac instances concurrently is going to be problematic.  So maybe we should use a named pipe in `.git/` to enable a `fac --continual` to listen for and respond to requests to build something else (as from a git hook).

This could also double as a lock to prevent uncontrolled simultaneous execution.

The downside as I see it is that it seems quite a bit of complexity added for what might be a very seldom used feature.

**Comment by pcn** [comment]
I'm thinking of something similar but I'm not sure that I would start with a named pipe.  In fact that's why I was tinkering with bigbro; I figured if I could emulate the build state machine, I could see about interposing a process or a function that would filter the targets and rules internal to `fac --continual`.  When I was thinking about that, it also made me want to apply the filter to the list of targets, so that if an un-staged file would affect the build, the build could be prevented with a log message.

**Comment by droundy** [comment]
What I'm thinking with the named pipe is that when fac runs it looks for the pipe, and if it is present and active, sends a message to the fac continual process telling it what to do.

**Comment by droundy** [comment]
I have added repository locking to fac.  The proximal cause of adding the locking was a need to make my `tests/continual.sh` test run reliably (by enabling polling until the build finished in the background).  But I think that with little work this locking should enable this bug to be closed, in that git hooks should be able to safely call fac even when `fac --continual` is running.

The only existing catch is in how fac behaves when it is unable to get the lock.  As a hokey first attempt, I just have fac wait a max of 15 seconds before giving up with an error message suggesting you remove the lock file by hand.  I don't want to wait indefinitely, but a hard cutoff could lead to bad behavior.  I could imagine making `fac --continual` wait silently forever (since it is designed to wait forever in any case).
