### ISSUE TITLE
Unnecessary rebuilds after directories are modified

### ISSUE THREAD

**Issue by ryderblue** [droundy/fac#13]
I noticed that when a build creates a file within a generated directory that repeated no-op builds cause unnecessary rebuilds since the timestamps between the filesystem and the .tum file seem to be out-of-sync. This is particularly true for nested directories.

For example, for the following .fac file:
```
$ cat > top.fac << EOF
| mkdir one
| mkdir one/two
< one
| mkdir one/two/three
< one/two
EOF
```
We build it once successfully:
```
$ fac -v
Using 12 jobs
 *** Building mkdir one/two
     because we have never built it.
 *** Building mkdir one/two/three
     because we have never built it.
1/3 [0.02s]: mkdir one
 *** Building mkdir one/two
     because we have never built it.
2/3 [0.02s]: mkdir one/two
 *** Building mkdir one/two/three
     because we have never built it.
3/3 [0.02s]: mkdir one/two/three
Build succeeded! 0:00.84
```
But then repeat it again and we fail due to timestamp differences:
```
$ fac -v
Using 12 jobs
 *** Building one
     because one has wrong output time.
1/3 [0.02s]: mkdir one
mkdir: cannot create directory `one': File exists
build failed: one
Build failed 3/3 failures
```
This issue could cause lots of unnecessary rebuilding for more complicated projects.

BTW, I really like this tool and would like to figure out how to use it to build complicated projects which would benefit from the dependency tracking.

**Comment by droundy** [comment]
Could you submit a test for this? Thanks for the big report!

**Comment by droundy** [comment]
BTW, by submit a test, I mean create a test script and send a pull request.

**Comment by droundy** [comment]
Wait, I see the problem.  When I added support for tracking mkdirs so we could clean them, it interacted weirdly with readdir tracking.  Right now dependency on a directory means that the command may call readdir on the directory, and under that assumption rebuilding is correct behavior.  I perhaps should distinguish between a command requiring that a directory exist and a command that reads that directory.

**Comment by ryderblue** [comment]
Please find the test case in the pull request I just created. I also included a proposed fix but there's likely a better way.

**Comment by droundy** [comment]
But there is a semantics question regarding directory dependencies that needs to be established. Specifically, there are two senses in which we may depend on a directory:

1. The directory must be present before the rule can run.

2. The rule must be re-run if the directory contents change.

The trouble is that currently we do not distinguish between these two kinds of dependencies.  I have two ideas for a way to distinguish between them, and am unsure which would be better.

A) We could make a distinction for directories between depending on `< directory/path` and depending on `directory/path/`.  The latter could mean number 2 above (depending on its contents) while the former could mean depending on the existence of the directory.  This would be a major bit of code, since we would have to thread these two kinds of dependencies throughout.  It could also be semantically confusing to people writing facfiles.  It also would introduce new constraints on build order that could be challenging.

B) I will write later as I need to go now.

**Comment by ryderblue** [comment]
Can you give some examples of a rule for #2 above (re-run if the directory contents change)? Won't the rule's inputs already be based on the contents of the directory (added to Git index) rather than anything that gets newly created in the directory?

**Comment by droundy** [comment]
Any rule that reads a directory will have a rule #2 dependency.  The simplest would be `| ls foo/ > bar`.  If you create or remove a file in foo, then you need to rerun this.  There are several tests with readdir in their name testing for this kind of dependency.

I also added a new and related test `bugs/readdir-generated-content.sh` which currently fails (thus living in `bugs/`), where we fail to rebuild when we should do so.  So there are bugs going in both directions.

**Comment by droundy** [comment]
A more realistic (and practical) example of needing to re-run when directory contents change is a rule that builds a fac-file by globbing for source files.  I often (in directories with latex files) run a little python script that looks basically like:

    for f in glob.glob('*.tex'):
      print('| pdflatex %s' % f)

Similar rules are handy for compiling C files, etc.  You really want this to re-run when there is a new file in the directory.  It does get re-run needlessly (e.g. if there are other files added), but there is no way for fac to tell that it doesn't need to be re-run.

**Comment by ryderblue** [comment]
If a directory's contents change which causes a rule to be re-run could there be way to run that rule for each input rather than the whole directory? This would be more efficient than your glob example since it would only process new changes. Maybe using a new operator (colon?) you could specify per-input rules which take an argument:
```
# run once when dir changes
| python gen.py
< src

# run for every input in dir when it changes
: python gen1.py $1
< src
```
This might be a better alternative to the potentially trickier alternative of using a trailing backslash (/) to indicate dependency on contents of dir.

**Comment by ryderblue** [comment]
Actually, I take back my suggestion. My thinking is influenced by GNU Make and it's hard to shake. If I'm not mistaken, I think the philosophy of Fac is to be as simple as possible and let the user generate .fac files to dynamically build more complex rules. I need to experiment with more complex code generator build rules to see how Makefile rules that I'm more familiar with could translate to Fac rules.

**Comment by ryderblue** [comment]
Here's my attempt at a simple codegen setup trying to use the same idioms you've demonstrated:
```
top.fac
src.py
src/
```
We create a `gen` dir to store generated code (.out extension). It's not to be stored in the repo.
```
$ cat top.fac
| mkdir gen
> gen

| python src.py > gen/gen.fac
< gen
< src
> gen/gen.fac
```
The `src.py` generates a `gen.fac` in the `gen` dir whenever the contents of `src` change.
```
$ cat src.py
import glob
for f in glob.glob('src/*'):
    f2 = f.split('/')[-1]
    print('| cat ../%s > %s.out\n< ../%s' % (f, f2, f))
```
Let's add our first file to `src`:
```
$ echo foo > src/foo && git add src/foo && fac -v
Using 12 jobs
 *** Building gen
     because we have never built it.
1/2 [0.02s]: mkdir gen
 *** Building gen/gen.fac
     because we have never built it.
2/2 [0.09s]: python src.py > gen/gen.fac
 *** Building cat ../src/foo > foo.out
     because we have never built it.
3/3 [0.02s]: cat ../src/foo > foo.out
Build succeeded! 0:00.13
```
Confirm that noop build has no side effects:
```
$ fac -v
Using 12 jobs
Build succeeded! 0:00.01
```
Let's add another file to `src`:
```
$ echo bar > src/bar && git add src/bar && fac -v
Using 12 jobs
 *** Building gen/gen.fac
     because src is definitely modified.
1/1 [0.07s]: python src.py > gen/gen.fac
 *** Building cat ../src/bar > bar.out
     because we have never built it.
2/2 [0.02s]: cat ../src/bar > bar.out
Build succeeded! 0:00.10
```
Now, if we try to perform noop build we get an error:
```
$ fac -v
Using 12 jobs
 *** Building gen
     because gen has wrong output time.
1/2 [0.02s]: mkdir gen
mkdir: cannot create directory `gen': File exists
build failed: gen
Failed to build 2 files.
```
However, a work-around is to use `mkdir -p ...` to ignore errors due to existing dirs:
```
$ head -2 top.fac
| mkdir -p gen
> gen
$ fac -v
Using 12 jobs
 *** Building gen
     because we have never built it.
1/2 [0.02s]: mkdir -p gen
 *** Building gen/gen.fac
     because gen has been rebuilt.
2/2 [0.10s]: python src.py > gen/gen.fac
Build succeeded! 0:00.13
```
Now it works and subsequent noop builds work as well:
```
$ fac -v
Using 12 jobs
Build succeeded! 0:00.01
```
The only annoyance is that we have to remember to use `mkdir -p ...` and any subsequent builds after a directory modification will always recreate the `gen/gen.fac` file unnecessarily.

Can you validate that this is a good idiom to follow, or would you recommend changes?

**Comment by ryderblue** [comment]
I created a pull request #15 for a codegen test which demonstrates some of the idioms commonly used. It could be updated over time to mimic more of the behaviors you'd see in traditional makefiles.

I've got to say I'm quite impressed with what you can do with Fac so far! It's been really easy to use and quite powerful.

**Comment by droundy** [comment]
Another option for this (which I appreciate) would be to mimic what I do with `getting-started.md`.  That is a tutorial document that is also run as a test suite (sadly, programmed myself by hand).  You might be able to work this into a really nice page documenting "best practices for generating facfiles."
