### ISSUE TITLE
Tag 0.5.3

### ISSUE THREAD

**Issue by dpercy** [droundy/fac#27]
I thought I'd try packaging fac for NixOS: https://github.com/NixOS/nixpkgs/pull/97868#discussion_r487490677.

Could you tag the latest commit (05c8507e3e4c5484a6f0e1393cea0c37d1d679ae) as 0.5.3, to match Cargo.toml?

Thanks!

**Comment by droundy** [comment]
I created the tag.  Do you use fac? I've not actually been aware for certain of anyone using fac who has not been a part of my research group...

**Comment by dpercy** [comment]
Thanks!

I've just started using fac, for personal projects. I was looking for something that's easy to learn, and that handles dependencies automatically. Having to manually update lists of dependencies tends to discourage me from splitting up files when it makes sense, so I think fac will help me avoid that.

**Comment by droundy** [comment]
I'm glad you're enjoying it! As you might guess, I use it for everything for just those reasons.
