### ISSUE TITLE
Git integration

### ISSUE THREAD

**Issue by chneukirchen** [droundy/fac#3]
Instead of guessing where `.git` resides, fac should use the output of `git rev-parse --show-toplevel`.

Also, fac currently does not work outside of git trees, perhaps the git integration should be disabled then.

**Comment by droundy** [comment]
I can definitely call git recourse. What is the advantage of doing so?

**Comment by droundy** [comment]
Oh, and without git, we would need some other way to identify .fac files to read. What do you suggest? We would need some way to distinguish between the original source files and those generated by build rules. I suppose we could introduce another file name convention for the latter...

**Comment by chneukirchen** [comment]
E.g. `.git` can be overridden by `$GIT_DIR`.

Good point on detecting .fac files... I thought just looking at all of them would be good. Didn't realize `fac` doesn't track build products itself.

**Comment by droundy** [comment]
Fac does track build products, but didn't read them until it is already
processing a .fac file.  If I changed that order, them I guess we could get
away with not having git to identify the input files.
