### ISSUE TITLE
Add tags to the GitHub repository

### ISSUE THREAD

**Issue by ngirard** [droundy/fac#30]
Adding the `build-tool` and `build-system` tags to the GitHub repository would make the project more discoverable.
It would be nice to give it a better description as well (currently: "Build system").

**Comment by droundy** [comment]
Lazy response: how do I set tags on a guy repository?

**Comment by ngirard** [comment]
By clicking on this button:
![Screenshot_20210405_172022](https://user-images.githubusercontent.com/98098/113590738-4a5c6600-9633-11eb-9cd4-c7a2deded707.png)

**Comment by droundy** [comment]
Thanks, I was looking in "settings" and not finding it!
