### ISSUE TITLE
Easier distribution

### ISSUE THREAD

**Issue by nikolay** [droundy/fac#4]
What prevents `fac` from being installed via just a `pip install --upgrade fac`?

**Comment by droundy** [comment]
It is not written in python? I've never tried to submit a non-python
program to pypi, but I would guess that it wouldn't be viewed terribly
favorably...

I do appreciate suggestions on how I might improve the installation
experience!

**Comment by nikolay** [comment]
@droundy Sorry, after a briefly look I thought that at least in parts `fac` is written in Python.

**Comment by droundy** [comment]
The configuration is done in python and some of the test scripts, so it was
a natural mistake!

**Comment by droundy** [comment]
I think this can be closed.  If you have ideas for easier distribution, please reopen!
