### ISSUE TITLE
OpenBSD support

### ISSUE THREAD

**Issue by ix** [droundy/fac#5]
Is support for OpenBSD planned at any point?

**Comment by droundy** [comment]
I have no plans on implementing support for OpenBSD myself.  I would be
happy to help with it, and could even install an OpenBSD virtual machine.
I put considerable effort into a freebsd port at one point, but it was
buggy (based on ktrace), and I ended up removing the code.  We could
resurrect that code if you (or someone else) wanted to work on it.  Another
possibility would be to make use of

 https://github.com/jacereda/fsatrace

which I think could work on OpenBSD.  It would have the disadvantage of not
working with statically linked executables, or anything that makes system
calls without passing through a dynamically linked C library (e.g. anything
written in go).  I've been thinking about adapting fsatrace to work with
fac, but with the goal primarily being windows.

**Comment by ix** [comment]
Since it's a non-issue on your end, I'm going to close this; however, I'll look into an OpenBSD port, and let you know if I find anything that might make it possible.
