### ISSUE TITLE
fac does not honor gitignore

### ISSUE THREAD

**Issue by flasheater** [droundy/fac#8]
In a scenario, where some file matching a pattern in `.gitignore` is also the input to some rule in fac, the build will fail, because the file has obviously not been added to git.

In my case the combination of `vim`, which generates temporary `.swp` files for files that are currently edited and `javac`, which takes whole directories as input, leads to the problem.
It makes sense, that fac assumes the `.swp` file is necessary for the output since `javac` reads it, so I am unsure as to how to fix this. If fac simply ignores input files in `.gitignore` there is a risk in other cases that it could miss critical files for the build.

A secondary issue is that `fac --git-add` seems to use `git add --force` under the hood, which is a mistake in my opinion, because it causes it to ignore `.gitignore`.

**Comment by droundy** [comment]
The current solution to these issues is to use a "c .swp" directive in your facfile.  This can be both clumsy and tedious, but is at least explicit.  The danger as I see it in treating .gitignore as "c" (or at least, ignoring indicated files as input) is that it could indeed miss a critical input file.  The trouble is that .gitignore is used both to indicate irrelevant files (e.g. file.swp or file~ from emacs) as well as output files (e.g. file.o or file.pdf).  The latter are often input files as well, and might in some cases not be generated files.    The --force on --git-add is intended for the same reason:  often it is needed.  But I don't use --git-add all that often myself, so could be convinced to turn this into an error case.

I can see one possible solution that might be some work but might disambiguate the difference:

Have fac generate and maintain its own section of .gitignore indicating all generated files.  Anything not in this section is treated as a cache file that is ignored.  The trouble with this proposal is that fac is now modifying a file in your repository, which seems like perhaps a poor precedent.  On the other hand, it would reduce effort in maintaining a manual list of globs for all generated files, which I find tedious (especially when using latex, which generates a lot of files that I don't care about).

**Comment by flasheater** [comment]
Regarding `--git-add`, there is at least one scenario where having it add files automatically is more harmful than an inconsistent build:
* secrets; gpg keys, api keys, passwords etc.

Other modern build tools mitigate this issue by taking ownership of a `build` directory where all output resides, but this approach does not seem to fit well with fac.
Another idea is to divorce fac from git and instead use a rule to the effect of:
```
| if [[ -n "$(git status | grep Untracked)" ]]; then exit 1 ; fi
```

**Comment by droundy** [comment]
I would recommend keeping passwords and keys outside of your repository directory in any case,  which would prevent any problem with fac adding them.  Although I suppose there are probably tools that force you to place them in a particular place.

Certainly `--git-add` is a dangerous option regardless of any interaction with .gitignore, and should simply be used with caution: either you need to not care what might be added, or you need to know what will be added.

**Comment by droundy** [comment]
I've gone ahead and made the `--git-add` flag not use the `-f` flag.  Regarding other uses for `.gitignore`, I haven't been able to come up with anything practical.  Ignoring dependencies on ignored files is obviously a poor idea, since most ignored files are generated dependencies (e.g. `*.o`).  Making fac generate a `.gitignore` file or update it sounds like a lot of effort for very little gain.

As far as tools like javac that apparently read files that they aren't going to use, these aren't going to work at all well with fac, and I don't see .gitignore being a better option than the 'c' directive of fac.

I think I will close this issue, since I've addressed the secondary issue with a code change, and I haven't been able to come up with a real plan for the primary issue.  Please feel free to reopen if you have a more specific request or idea for improvement.

**Comment by flasheater** [comment]
Yes, I have no clue how to resolve this cleanly as well. 

I believe that facs integration with git and its use as a lower level component of the actual build system (whatever the user happens to choose) are diametrically opposed to each other and will cause issues like this down the road.

Are you satisfied with the interaction of --git-add and --continual now that -f is removed? Alternatively, I would be satisfied with a big,fat warning in the man page next to --git-add.

Regarding javac and tools like it, I have to test, think and learn a little more before forming an opinion. My suspicion is that this should be addressed by keeping the scope of each rule minimal.
